"""
Utilities for generating unique identifiers.
"""

import time
import random
import string
from uuid import uuid4
from typing import Optional


def generate_id(prefix: str = "", length: int = 8) -> str:
    """
    Generate a random ID with optional prefix.
    
    Args:
        prefix: Optional prefix for the ID
        length: Length of the random part
        
    Returns:
        Generated ID string
    """
    random_part = ''.join(random.choices(string.ascii_lowercase + string.digits, k=length))
    return f"{prefix}{random_part}" if prefix else random_part


def generate_uuid() -> str:
    """Generate a UUID4 string."""
    return str(uuid4())


def generate_run_id(prefix: str = "run") -> str:
    """
    Generate a unique run ID.
    
    Args:
        prefix: Prefix for the run ID
        
    Returns:
        Generated run ID
    """
    timestamp = int(time.time() * 1000)  # milliseconds
    random_part = generate_id(length=6)
    return f"{prefix}_{timestamp}_{random_part}"


def generate_span_id(prefix: str = "span") -> str:
    """
    Generate a unique span ID.
    
    Args:
        prefix: Prefix for the span ID
        
    Returns:
        Generated span ID
    """
    return f"{prefix}_{generate_id(length=12)}"


def generate_trace_id() -> str:
    """Generate a trace ID compatible with distributed tracing standards."""
    return uuid4().hex


def generate_short_id(length: int = 8) -> str:
    """
    Generate a short random ID suitable for display.
    
    Args:
        length: Length of the ID
        
    Returns:
        Short random ID
    """
    # Use alphanumeric characters excluding similar looking ones
    chars = "23456789abcdefghjkmnpqrstuvwxyz"
    return ''.join(random.choices(chars, k=length))


def extract_timestamp_from_id(id_string: str) -> Optional[int]:
    """
    Extract timestamp from IDs generated by generate_run_id.
    
    Args:
        id_string: The ID string to parse
        
    Returns:
        Timestamp in milliseconds if found, None otherwise
    """
    try:
        parts = id_string.split('_')
        if len(parts) >= 2:
            return int(parts[1])
    except (ValueError, IndexError):
        pass
    return None


class IDGenerator:
    """
    Configurable ID generator with different strategies.
    """
    
    def __init__(self, prefix: str = "", use_timestamp: bool = True):
        self.prefix = prefix
        self.use_timestamp = use_timestamp
        self._counter = 0
    
    def next_id(self) -> str:
        """Generate the next ID."""
        parts = []
        
        if self.prefix:
            parts.append(self.prefix)
        
        if self.use_timestamp:
            parts.append(str(int(time.time() * 1000)))
        
        # Add counter for uniqueness
        self._counter += 1
        parts.append(f"{self._counter:04d}")
        
        # Add random component
        parts.append(generate_id(length=4))
        
        return "_".join(parts)
    
    def reset_counter(self) -> None:
        """Reset the internal counter."""
        self._counter = 0
